services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./api:/usr/src/app # Monta solo la carpeta 'api' dentro del contenedor
      - /usr/src/app/node_modules # Mantén este volumen para evitar conflictos
      - /var/run/docker.sock:/var/run/docker.sock # socket de docker
    environment:
      - NODE_ENV=development
    container_name: api-container

  k6:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts
    entrypoint: tail -f /dev/null
    container_name: k6-container