version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  k6:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts
    entrypoint: tail -f /dev/null